#!/usr/bin/env bash
set -e # halt script on error

bundle exec jekyll build
bundle exec htmlproofer --file-ignore ./_site/client/odisha/dashboard/index.html ./_site --disable-external 

# --check-html

#bundle exec htmlproofer --url-ignore "/simlab.org/" --file-ignore ./_site/client/odisha/dashboard/index.html ./_site